- hosts: all
  sudo: True

  vars:
   solr_port: '8983'

  tasks:

    - name: Creates destination directory
      file: state=directory mode=0700 dest=/root/.ssh/
      
    - name: Pushes user's rsa key to root's vagrant box (it's ok if this TASK fails)
      action: copy src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      register: rsa
      ignore_errors: yes

    - name: Pushes user's dsa key to root's vagrant box (it's NOT ok if both TASKs fail)
      action: copy src=~/.ssh/id_dsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      when_failed: $rsa

    - name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
      action: command host -t A ansible.cc
      register: ns
      ignore_errors: yes

    - name: Pushes new resolver configuration is resolver fails
      action: lineinfile regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
      when_failed: $ns

    - name: Checks if resolver is working properly with new nameserver
      action: command host -t A ansible.cc

    - name: Install required packages
      apt: pkg=$item state=installed update_cache=yes
      with_items:
        - tomcat6
        - solr-common
        - solr-tomcat

    - name: Setup Tomcat config 
      template: src=templates/etc-tomcat6-server.xml.j2 dest=/etc/tomcat6/server.xml backup=yes

#    - name: Disable default solr webapp
#      file: path=/var/lib/tomcat6/conf/Catalina/localhost/solr.xml state=absent

    - name: Reload tomcat
      service: name=tomcat6 state=restarted


